/* eslint-env serviceworker */
/* This file is generated by scripts/generate-service-worker.mjs. */
(function () {
  "use strict";

  var VERSION = "2026-07-04-4";
  var CACHE_PREFIX = "cwlblog";
  var PRECACHE = CACHE_PREFIX + "-precache-" + VERSION;
  var RUNTIME = CACHE_PREFIX + "-runtime-" + VERSION;
  var OFFLINE_URL = "/offline.html";
  var PRECACHE_URLS = [
      "/",
      "/offline.html",
      "/manifest.webmanifest",
      "/images/favicon.png",
      "/css/fontawesome-all.min.css",
      "/css/coder.css",
      "/css/assistant.css",
      "/webfonts/fa-brands-400.subset.woff2",
      "/webfonts/fa-solid-900.subset.woff2",
      "/css/tools.css",
      "/css/trust.css",
      "/js/error-handler.js",
      "/js/utils.js",
      "/js/i18n.js",
      "/js/coder.js",
      "/js/search-loader.js",
      "/js/subscribe.js",
      "/js/assistant-loader.js",
      "/js/pwa-register.js"
  ];
  var PWA_CACHE_STRATEGIES = Object.freeze({
      "CACHE_FIRST": "cache-first",
      "NETWORK_FIRST": "network-first",
      "NETWORK_ONLY": "network-only",
      "STALE_WHILE_REVALIDATE": "stale-while-revalidate"
  });
  var PWA_CACHE_POLICY_MATRIX = Object.freeze([
      {
          "category": "navigation",
          "strategy": "network-first",
          "cacheable": true
      },
      {
          "category": "static-asset",
          "strategy": "cache-first",
          "cacheable": true
      },
      {
          "category": "search-index",
          "strategy": "stale-while-revalidate",
          "cacheable": true
      },
      {
          "category": "fresh-data",
          "strategy": "network-only",
          "cacheable": false
      },
      {
          "category": "sensitive-or-external",
          "strategy": "network-only",
          "cacheable": false
      }
  ]);
  var STATIC_ASSET_RE = /\.(?:css|js|mjs|png|jpe?g|webp|avif|gif|svg|ico|woff2?|ttf|webmanifest)$/i;
  var HTML_RE = /\.html$/i;
  var SENSITIVE_QUERY_RE = /(?:^|[?&])(?:access_token|api[_-]?key|auth|authorization|key|secret|signature|token)=/i;
  var SENSITIVE_HEADER_NAMES = ["authorization", "cookie", "proxy-authorization", "x-api-key", "x-auth-token"];

  function normalizeOrigin(origin) {
    return String(origin || self.location.origin).replace(/\/+$/, "");
  }

  function requestUrl(input) {
    if (typeof input === "string" || input instanceof URL) {
      return String(input);
    }
    return String(input && input.url || "/");
  }

  function requestMethod(input) {
    if (typeof input === "string" || input instanceof URL) {
      return "GET";
    }
    return String(input && input.method || "GET").toUpperCase();
  }

  function requestMode(input) {
    if (typeof input === "string" || input instanceof URL) {
      return "";
    }
    return String(input && input.mode || "");
  }

  function normalizeHeaders(headers) {
    var entries = [];
    if (!headers) return entries;
    if (typeof headers.forEach === "function") {
      headers.forEach(function (value, key) {
        entries.push([String(key).toLowerCase(), String(value)]);
      });
      return entries;
    }
    if (Array.isArray(headers)) {
      return headers.map(function (entry) {
        return [String(entry[0]).toLowerCase(), String(entry[1])];
      });
    }
    Object.keys(headers).forEach(function (key) {
      entries.push([String(key).toLowerCase(), String(headers[key])]);
    });
    return entries;
  }

  function hasSensitiveHeader(headers) {
    return normalizeHeaders(headers).some(function (entry) {
      return SENSITIVE_HEADER_NAMES.indexOf(entry[0]) !== -1;
    });
  }

  function policy(strategy, category, reason, cacheable) {
    return {
      strategy: strategy,
      category: category,
      reason: reason,
      cacheable: cacheable === undefined ? strategy !== PWA_CACHE_STRATEGIES.NETWORK_ONLY : cacheable
    };
  }

  function classifyPwaRequest(input, options) {
    var opts = options || {};
    var origin = normalizeOrigin(opts.origin);
    var url = new URL(requestUrl(input), origin + "/");
    var method = requestMethod(input);
    var mode = requestMode(input);
    var headers = typeof input === "string" || input instanceof URL ? opts.headers : input && input.headers;

    if (method !== "GET") {
      return policy(PWA_CACHE_STRATEGIES.NETWORK_ONLY, "sensitive-or-external", "non-get request", false);
    }
    if (url.origin !== origin) {
      return policy(PWA_CACHE_STRATEGIES.NETWORK_ONLY, "sensitive-or-external", "external origin", false);
    }
    if (SENSITIVE_QUERY_RE.test(url.search)) {
      return policy(PWA_CACHE_STRATEGIES.NETWORK_ONLY, "sensitive-or-external", "sensitive query", false);
    }
    if (hasSensitiveHeader(headers)) {
      return policy(PWA_CACHE_STRATEGIES.NETWORK_ONLY, "sensitive-or-external", "sensitive header", false);
    }
    if (url.pathname === "/search-index.json") {
      return policy(PWA_CACHE_STRATEGIES.STALE_WHILE_REVALIDATE, "search-index", "search index");
    }
    if (url.pathname === "/data/relay-providers.json" || url.pathname.indexOf("/api/") === 0) {
      return policy(PWA_CACHE_STRATEGIES.NETWORK_ONLY, "fresh-data", "fresh data", false);
    }
    if (mode === "navigate" || url.pathname === "/" || url.pathname.endsWith("/") || HTML_RE.test(url.pathname)) {
      return policy(PWA_CACHE_STRATEGIES.NETWORK_FIRST, "navigation", "navigation");
    }
    if (STATIC_ASSET_RE.test(url.pathname)) {
      return policy(PWA_CACHE_STRATEGIES.CACHE_FIRST, "static-asset", "static asset");
    }
    return policy(PWA_CACHE_STRATEGIES.NETWORK_ONLY, "sensitive-or-external", "unmatched request", false);
  }

  function canCache(response) {
    return response && response.ok && (response.type === "basic" || response.type === "default");
  }

  async function cachePut(cacheName, request, response) {
    if (!canCache(response)) return;
    var cache = await caches.open(cacheName);
    await cache.put(request, response.clone());
  }

  async function networkFirst(request) {
    try {
      var response = await fetch(request);
      await cachePut(RUNTIME, request, response);
      return response;
    } catch (error) {
      return (await caches.match(request)) || (await caches.match(OFFLINE_URL)) || Response.error();
    }
  }

  async function cacheFirst(request) {
    var cached = await caches.match(request);
    if (cached) return cached;
    var response = await fetch(request);
    await cachePut(RUNTIME, request, response);
    return response;
  }

  async function staleWhileRevalidate(request, event) {
    var cached = await caches.match(request);
    var fetched = fetch(request).then(function (response) {
      return cachePut(RUNTIME, request, response).then(function () {
        return response;
      });
    });
    if (cached) {
      event.waitUntil(fetched.catch(function () {}));
      return cached;
    }
    return fetched;
  }

  self.addEventListener("install", function (event) {
    event.waitUntil(caches.open(PRECACHE).then(function (cache) {
      return cache.addAll(PRECACHE_URLS);
    }).then(function () {
      return self.skipWaiting();
    }));
  });

  self.addEventListener("activate", function (event) {
    event.waitUntil(caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (key) {
        return key.indexOf(CACHE_PREFIX + "-") === 0 && key !== PRECACHE && key !== RUNTIME;
      }).map(function (key) {
        return caches.delete(key);
      }));
    }).then(function () {
      return self.clients.claim();
    }));
  });

  self.addEventListener("fetch", function (event) {
    var decision = classifyPwaRequest(event.request);
    if (decision.strategy === PWA_CACHE_STRATEGIES.NETWORK_ONLY) {
      event.respondWith(fetch(event.request));
      return;
    }
    if (decision.strategy === PWA_CACHE_STRATEGIES.NETWORK_FIRST) {
      event.respondWith(networkFirst(event.request));
      return;
    }
    if (decision.strategy === PWA_CACHE_STRATEGIES.STALE_WHILE_REVALIDATE) {
      event.respondWith(staleWhileRevalidate(event.request, event));
      return;
    }
    event.respondWith(cacheFirst(event.request));
  });

  self.CWL_PWA_CACHE_POLICY = {
    VERSION: VERSION,
    OFFLINE_URL: OFFLINE_URL,
    PRECACHE_URLS: PRECACHE_URLS.slice(),
    PWA_CACHE_STRATEGIES: PWA_CACHE_STRATEGIES,
    PWA_CACHE_POLICY_MATRIX: PWA_CACHE_POLICY_MATRIX,
    classifyPwaRequest: classifyPwaRequest
  };
}());
