import test from "node:test";
import assert from "node:assert/strict";
import { readFile, rm } from "node:fs/promises";
import { join } from "node:path";
import vm from "node:vm";

import { renderServiceWorker, SERVICE_WORKER_VERSION } from "../src/service-worker-template.mjs";
import {
  checkGeneratedServiceWorker,
  parseArgs,
  writeGeneratedServiceWorker,
} from "../scripts/generate-service-worker.mjs";
import { PWA_PRECACHE_URLS } from "../src/pwa-precache.mjs";
import { classifyPwaRequest } from "../src/pwa-cache-policy.mjs";

const ROOT = join(import.meta.dirname, "..");

function evaluateServiceWorker(source) {
  const listeners = {};
  const sandbox = {
    URL,
    Response,
    Promise,
    console,
    self: {
      location: { origin: "https://wenliang844.github.io" },
      addEventListener(type, listener) {
        listeners[type] = listener;
      },
      skipWaiting() {
        return Promise.resolve();
      },
      clients: {
        claim() {
          return Promise.resolve();
        },
      },
    },
    caches: {
      open() {
        return Promise.resolve({ addAll: () => Promise.resolve(), put: () => Promise.resolve() });
      },
      keys() {
        return Promise.resolve([]);
      },
      match() {
        return Promise.resolve(undefined);
      },
      delete() {
        return Promise.resolve(true);
      },
    },
    fetch() {
      return Promise.resolve(new Response(""));
    },
  };
  sandbox.self.self = sandbox.self;
  vm.runInNewContext(source, sandbox, { filename: "service-worker.js" });
  return { listeners, policy: sandbox.self.CWL_PWA_CACHE_POLICY };
}

test("service worker renderer emits the committed root artifact", async () => {
  const source = await readFile(join(ROOT, "service-worker.js"), "utf8");

  assert.equal(source, `${renderServiceWorker()}\n`);
  assert.match(source, /generated by scripts\/generate-service-worker\.mjs/);
  assert.match(source, new RegExp(`var VERSION = "${SERVICE_WORKER_VERSION.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}";`));
});

test("generated service worker exports the source precache and request policy", () => {
  const { listeners, policy } = evaluateServiceWorker(renderServiceWorker());

  assert.equal(typeof listeners.install, "function");
  assert.equal(typeof listeners.activate, "function");
  assert.equal(typeof listeners.fetch, "function");
  assert.deepEqual(JSON.parse(JSON.stringify(policy.PRECACHE_URLS)), PWA_PRECACHE_URLS);
  assert.deepEqual(
    JSON.parse(JSON.stringify(policy.classifyPwaRequest("/data/relay-providers.json"))),
    classifyPwaRequest("/data/relay-providers.json"),
  );
  assert.deepEqual(
    JSON.parse(JSON.stringify(policy.classifyPwaRequest("/tools/?api_key=secret"))),
    classifyPwaRequest("/tools/?api_key=secret"),
  );
});

test("service worker generator supports write and check modes", async () => {
  const outputPath = "temp/test-generated-service-worker.js";
  await rm(join(ROOT, outputPath), { force: true });

  assert.deepEqual(parseArgs([]), { check: false, outputPath: "service-worker.js" });
  assert.deepEqual(parseArgs(["--check", "--out", outputPath]), { check: true, outputPath });
  assert.throws(() => parseArgs(["--out"]), /--out requires a file path/);

  await writeGeneratedServiceWorker(outputPath);
  assert.equal(await readFile(join(ROOT, outputPath), "utf8"), `${renderServiceWorker()}\n`);
  assert.deepEqual(await checkGeneratedServiceWorker(outputPath), { outputPath, ok: true });

  await rm(join(ROOT, outputPath), { force: true });
});
